loglevel: info

http:
  port: 8080

mongo:
  connectionstring: mongodb://username:password@0.0.0.0:27017
  database: irc-reader
  collection: twitch-irc-channels

nats:
  url: 0.0.0.0:4222
  topic:
    emotes: stats.emotes.global

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
