loglevel: info

http:
  port: ${port}

mongo:
  connectionstring: ${mongo_uri}
  database: ${mongo_database}
  collection: ${mongo_collection}
  username: ${mongo_username}
  password: ${mongo_password}

nats:
  url: ${nats_url}
  topic:
    api: ${nats_bot_api}

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
