loglevel: info

ratelimit:
  limit: 20
  reset: 20

twitch:
  user: justinfan77777
  oauth: oauth

nats:
  url: 0.0.0.0:4222
  topic:
    raw: irc.raw.twitch

mongo:
  connectionstring: mongodb://username:password@0.0.0.0:27017
  collection: twitch-irc-channels

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
