loglevel: info
environment: dev

twitch:
  clientid: ""
  clientsecret: ""
  refreshtoken: ""
  redirecturi: "http://localhost:7777"
  state: ""

kube:
  namespace: default
  oauthsecret: twitch-irc-oauth

http:
  port: 7777

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
