loglevel: info

twitch:
  user: justinfan77777
  oauth: oauth

http:
  port: 8080

mongo:
  connectionstring: mongodb://username:password@0.0.0.0:27017
  database: irc-reader
  collection: twitch-irc-channels

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
