loglevel: info

nats:
  url: 0.0.0.0:4222
  stream: twitchIRC
  consumer: stats-aggregator
  topic:
    raw: irc.raw.twitch.>

mongo:
  connectionstring: mongodb://username:password@0.0.0.0:27017
  database: irc-stats
  collection: twitch-irc-stats

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
